# TCP Configuration
HOST = "localhost"
PORT = 9999
BUFFER_SIZE = 4096
DELIMITER = "||"

# Indicator Periods
RSI_PERIOD = 14
EMA_FAST = 12
EMA_SLOW = 26
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BOLL_PERIOD = 20
BOLL_STD = 2.0
ATR_PERIOD = 14

# Machine Learning Settings
TRAINING_WINDOW = 5000
XGB_N_ESTIMATORS = 100
XGB_MAX_DEPTH = 6
XGB_LEARNING_RATE = 0.01
XGB_SUBSAMPLE = 0.8
XGB_COLSAMPLE_BYTREE = 0.8
XGB_EARLY_STOPPING_ROUNDS = 50
XGB_N_SPLITS = 5
XGB_PREDICTION_THRESHOLD = 0.5
XGB_FINAL_MODEL_MULTIPLIER = 1.1
XGB_RANDOM_STATE = 42
RETRAIN_INTERVAL = 100

# Signal Generation Settings
SIGNAL_DEFAULT_THRESHOLD = 0.55
SIGNAL_THRESHOLD_MIN = 0.5
SIGNAL_THRESHOLD_MAX = 0.7